module.exports = {
  SESSION_SECRET: process.env.SESSION_SECRET,
  TWILIO_PHONE: process.env.TWILIO_PHONE,
  TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID,
  TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN,
  AUTHY_API_KEY: process.env.AUTHY_API_KEY,
  VERIFY_SERVICE_SID: process.env.VERIFY_SERVICE_SID,
  TWILIO_MESSAGING_SERVICES_SID: process.env.TWILIO_MESSAGING_SERVICES_SID,
  GOOGLE_OAUTH_CLIENT_ID: process.env.GOOGLE_OAUTH_CLIENT_ID,
  GOOGLE_API_KEY: process.env.GOOGLE_API_KEY
};
